---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    default_motd: "Welcome to {{ ansible_hostname }}"

  tasks:
    - name: Stat /etc/motd
      ansible.builtin.stat:
        path: /etc/motd
      register: r_motd

    - name: Verify existence of /etc/motd
      ansible.builtin.assert:
        that:
          - r_motd.stat.exists
        fail_msg: /etc/motd not found on system

    - name: Verify correct contents of /etc/motd
      ansible.builtin.assert:
        that:
          - r_motd.stat.checksum == "{{ default_motd | ansible.builtin.sha1 }}"
        fail_msg: /etc/motd contents not correct
