---
- name: Prepare container instances
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Install prerequistes
      ansible.builtin.package:
        name: "{{ required_packages }}"
        state: present
      when: required_packages is defined
